// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwb8obSh9-D43I84bUjy5f8WIgZI-tlYU',
    appId: '1:410674076254:web:a2aa23fb8668bcf2d872cf',
    messagingSenderId: '410674076254',
    projectId: 'cred-books',
    authDomain: 'cred-books.firebaseapp.com',
    storageBucket: 'cred-books.appspot.com',
    measurementId: 'G-KFHKJPHRM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpODDqk0ykOaH8nyS_4hgONH4hifqMYkg',
    appId: '1:410674076254:android:a9952971120e6e56d872cf',
    messagingSenderId: '410674076254',
    projectId: 'cred-books',
    storageBucket: 'cred-books.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJGdBlHSHNnrK34wTcLAdBq2YQ-eVZtlE',
    appId: '1:410674076254:ios:ad2eccbf52cf5eccd872cf',
    messagingSenderId: '410674076254',
    projectId: 'cred-books',
    storageBucket: 'cred-books.appspot.com',
    iosClientId: '410674076254-mlac33j8v7nr9q3iai5sg62pjdri7bo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.credBooks',
  );
}
